
//[TruckTypeToSpawn, TruckWheelsToDamage]
#define ME_TRUCK_SPAWN_DETAILS [[ME_REPAIR_VEHICLE_TYPE, ME_REPAIR_VEHICLE_WHEELS], [ME_FUEL_VEHICLE_TYPE, ME_FUEL_VEHICLE_WHEELS]]

#define ME_REPAIR_VEHICLE_TYPE "UK3CB_CW_SOV_O_EARLY_Gaz66_Repair"
#define ME_REPAIR_VEHICLE_WHEELS ["hitlfwheel", "hitlf2wheel", "hitrfwheel", "hitrf2wheel"]

#define ME_FUEL_VEHICLE_TYPE "UK3CB_CW_SOV_O_EARLY_VDV_Kraz255_Fuel"
#define ME_FUEL_VEHICLE_WHEELS ["hitlfwheel", "hitlf2wheel", "hitlmwheel", "hitrfwheel", "hitrf2wheel", "hitrmwheel"]
//OreoNacho - _Kraz255_Fuel
//Ural_Fuel

//TODO: Could clean up by setting a global var that combines these instead of this long line const
#define ME_TRUCK_LOCATIONS [ME_TRUCK_FUEL_TANKS_SPAWN, ME_TRUCK_MAIN_WAREHOUSE_SPAWN, ME_TRUCK_E_GARAGE_1ST_SPAWN, ME_TRUCK_E_GARAGE_2ND_SPAWN, ME_TRUCK_W_GARAGE_1ST_SPAWN, ME_TRUCK_S_GARAGE_1ST_SPAWN, ME_TRUCK_S_GARAGE_2ND_SPAWN]

//Fuel tanks location
#define ME_TRUCK_FUEL_TANKS_SPAWN [ME_FUEL_POS_1, ME_FUEL_ROT_1]
#define ME_FUEL_POS_1 [11946.582, 12481.896, 0]
#define ME_FUEL_ROT_1 21

//Warehouse location
#define ME_TRUCK_MAIN_WAREHOUSE_SPAWN [ME_FUEL_POS_2, ME_FUEL_ROT_2]
#define ME_FUEL_POS_2 [12053.16, 12449.794, 0]
#define ME_FUEL_ROT_2 111

//Eastern Garage Slot #2
#define ME_TRUCK_E_GARAGE_1ST_SPAWN [ME_TRUCK_E_GARAGE_1ST_POS, ME_TRUCK_E_GARAGE_1ST_ROT]
#define ME_TRUCK_E_GARAGE_1ST_POS [12456.072, 12546.477, 0.452]
#define ME_TRUCK_E_GARAGE_1ST_ROT 188

//Eastern Garage Slot #3
#define ME_TRUCK_E_GARAGE_2ND_SPAWN [ME_TRUCK_E_GARAGE_2ND_POS, ME_TRUCK_E_GARAGE_2ND_ROT]
#define ME_TRUCK_E_GARAGE_2ND_POS [12461.923, 12545.33, 0.373]
#define ME_TRUCK_E_GARAGE_2ND_ROT 188

//Western Garage Slot #1
#define ME_TRUCK_W_GARAGE_1ST_SPAWN [ME_TRUCK_W_GARAGE_1ST_POS, ME_TRUCK_W_GARAGE_1ST_ROT]
#define ME_TRUCK_W_GARAGE_1ST_POS [12129.947, 12657.562, 0]
#define ME_TRUCK_W_GARAGE_1ST_ROT 113

//Southern Garage Slot #1
#define ME_TRUCK_S_GARAGE_1ST_SPAWN [ME_TRUCK_S_GARAGE_1ST_POS, ME_TRUCK_S_GARAGE_1ST_ROT]
#define ME_TRUCK_S_GARAGE_1ST_POS [11830.778, 12461.354, 0]
#define ME_TRUCK_S_GARAGE_1ST_ROT 113

//Southern Garage Slot #2
#define ME_TRUCK_S_GARAGE_2ND_SPAWN [ME_TRUCK_S_GARAGE_1ST_POS, ME_TRUCK_S_GARAGE_1ST_ROT]
#define ME_TRUCK_S_GARAGE_2ND_POS [11873.992, 12477.114, 0]
#define ME_TRUCK_S_GARAGE_2ND_ROT 113


#define ME_TRUCK_INIT_DAMAGE "messyEvac\scripts\trucks\damageTruck.sqf"
#define ME_RESPAWN_VEHICLE_SETUP "messyEvac\scripts\trucks\damageRespawnVehicles.sqf"